#pragma once

#define CONFIG_LV_DISPLAY_ORIENTATION 2

#define CONFIG_LV_DISP_PIN_DC 15
#define DISP_SPI_MOSI 23
#define DISP_SPI_MISO 38
#define DISP_SPI_CLK 18

#define SPI_TFT_CLOCK_SPEED_HZ (16 * 1000 * 1000)

#define DISP_BUF_SIZE (CONFIG_LV_HOR_RES_MAX * 40)

#define SPI_BUS_MAX_TRANSFER_SZ (DISP_BUF_SIZE * 2)

#define SPI_TFT_SPI_MODE (0)

#define DISP_SPI_INPUT_DELAY_NS 0

#define DISP_SPI_CS 5

#define CONFIG_I2C_SDA 21
#define CONFIG_I2C_SCL 22
#define TOUCH_I2C_SPEED_HZ 400000
